"""add user preferred_language

Revision ID: 0fe3bc2767cd
Revises: 273bcc88285f
Create Date: 2026-09-06 23:39:30.008930

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0fe3bc2767cd'
down_revision: Union[str, None] = '273bcc88285f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # The enum type must exist before a column can use it — sa.Enum(...)
    # only auto-creates via Base.metadata.create_all(), not from inside a
    # migration's op.add_column. server_default backfills existing rows;
    # dropped after since the ORM column default (PreferredLanguage.bn)
    # covers new inserts going forward.
    preferred_language_enum = sa.Enum('bn', 'en', name='preferredlanguage')
    preferred_language_enum.create(op.get_bind(), checkfirst=True)
    op.add_column(
        'users',
        sa.Column(
            'preferred_language',
            preferred_language_enum,
            nullable=False,
            server_default='bn',
        ),
    )
    op.alter_column('users', 'preferred_language', server_default=None)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'preferred_language')
    sa.Enum(name='preferredlanguage').drop(op.get_bind(), checkfirst=True)
    # ### end Alembic commands ###
