"""complaint draft ownership and cascade fks

Revision ID: 273bcc88285f
Revises: 90ef7290efeb
Create Date: 2026-09-06 23:33:21.749699

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '273bcc88285f'
down_revision: Union[str, None] = '90ef7290efeb'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # complaint_drafts predates per-user ownership scoping. Add the column
    # nullable first, drop any pre-existing rows that can't be attributed to
    # a user (there's no way to backfill ownership for those), then enforce
    # NOT NULL for everything going forward.
    op.add_column('complaint_drafts', sa.Column('user_id', sa.Integer(), nullable=True))
    op.execute('DELETE FROM complaint_drafts WHERE user_id IS NULL')
    op.alter_column('complaint_drafts', 'user_id', nullable=False)
    op.create_index(op.f('ix_complaint_drafts_user_id'), 'complaint_drafts', ['user_id'], unique=False)
    op.drop_constraint(op.f('complaint_drafts_conversation_turn_id_fkey'), 'complaint_drafts', type_='foreignkey')
    op.create_foreign_key(None, 'complaint_drafts', 'users', ['user_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(None, 'complaint_drafts', 'conversation_turns', ['conversation_turn_id'], ['id'], ondelete='SET NULL')
    op.drop_constraint(op.f('conversation_turns_conversation_id_fkey'), 'conversation_turns', type_='foreignkey')
    op.create_foreign_key(None, 'conversation_turns', 'conversations', ['conversation_id'], ['id'], ondelete='CASCADE')
    op.drop_constraint(op.f('conversations_user_id_fkey'), 'conversations', type_='foreignkey')
    op.create_foreign_key(None, 'conversations', 'users', ['user_id'], ['id'], ondelete='CASCADE')
    op.drop_constraint(op.f('reminders_user_id_fkey'), 'reminders', type_='foreignkey')
    op.create_foreign_key(None, 'reminders', 'users', ['user_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'reminders', type_='foreignkey')
    op.create_foreign_key(op.f('reminders_user_id_fkey'), 'reminders', 'users', ['user_id'], ['id'])
    op.drop_constraint(None, 'conversations', type_='foreignkey')
    op.create_foreign_key(op.f('conversations_user_id_fkey'), 'conversations', 'users', ['user_id'], ['id'])
    op.drop_constraint(None, 'conversation_turns', type_='foreignkey')
    op.create_foreign_key(op.f('conversation_turns_conversation_id_fkey'), 'conversation_turns', 'conversations', ['conversation_id'], ['id'])
    op.drop_constraint(None, 'complaint_drafts', type_='foreignkey')
    op.drop_constraint(None, 'complaint_drafts', type_='foreignkey')
    op.create_foreign_key(op.f('complaint_drafts_conversation_turn_id_fkey'), 'complaint_drafts', 'conversation_turns', ['conversation_turn_id'], ['id'])
    op.drop_index(op.f('ix_complaint_drafts_user_id'), table_name='complaint_drafts')
    op.drop_column('complaint_drafts', 'user_id')
    # ### end Alembic commands ###
